### PR TITLE
feat: Introduce logs in json format using log/slog

### PR DESCRIPTION
**Pull request by hiddenmarten**
## Summary
https://github.com/TwiN/k8s-ttl-controller/issues/99

## Checklist

- [X] Tested and/or added tests to validate that the changes work as intended, if applicable.
- [X] Updated documentation in `README.md`, if applicable.

### CODE REVIEW

**Comment by hiddenmarten** [comment]
Reimplemented from scratch to achieve a closer resemblance to the initial implementation and to avoid adding external dependencies.

**Comment by TwiN** [comment]
This is going to sound a little weird, but I'm actually in the process of migrating my Go projects to use [my own logging library](https://github.com/TwiN/logr). I haven't had the opportunity to add support for JSON logs yet, but I'd be more than receptive to the idea of letting somebody else implement it if you're willing to take on the challenge.

That being said, since you re-implemented it in a way that makes the changes much smaller (as opposed to the logrus approach you initially took), I'm okay with merging the current implementation.

What do you think? Do you want the current implementation, or would you be willing to try implementing JSON logs on [logr](https://github.com/TwiN/logr)? Either way, I'm very thankful for the effort you're putting into this, so please don't hesitate if you'd rather just go for the current implementation - no hard feelings!

**Comment by hiddenmarten** [comment]
I'd suggest merging it as is, with a pinky promise from me to review your library later. I should have time over the weekend. :)

Thank you so much for the super fast review - I really appreciate it!

**Review by TwiN — APPROVED** [review]

**Comment by TwiN** [comment]
@hiddenmarten Pleasure's mine - and there's no need to impose such a short deadline on yourself. With Christmas and New Year just around the corner, feel free to look into it after the Holidays if you have other matters to take care of :)

**Pull request merged**
